version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    container_name: expenses_list
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/expenses_list
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - fksolutions
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - db

  db:
    image: postgres:11.7
    container_name: expenses_list_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - fksolutions
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

networks:
  fksolutions:
    name: fksolutions
    driver: bridge

volumes:
  postgres_data: