version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    container_name: expenses_list
    command: >
      sh -c "python manage.py migrate && 
             python manage.py collectstatic --no-input --clear && 
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/usr/src/apps/api/staticfiles
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - fksolutions
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: expenses_list_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - fksolutions
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/apps/api/staticfiles
    ports:
      - "1337:80"
    networks:
      - fksolutions
    depends_on:
      - api

networks:
  fksolutions:
    name: fksolutions
    driver: bridge

volumes:
  postgres_data:
  static_volume: