# Generated by Django 4.1.1 on 2022-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
