# Generated by Django 4.1.1 on 2022-09-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shopping_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='unit',
            field=models.IntegerField(choices=[(1, 'oz'), (2, 'lb'), (3, 'kg'), (4, 'pkg'), (5, 'gal'), (6, 'lit'), (7, 'uni')], default=1),
        ),
    ]
