# Generated by Django 4.1.1 on 2022-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_purchases_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
