# Generated by Django 4.1 on 2022-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_category_products_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='category',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='productstype',
            name='type',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
