# Generated by Django 4.1 on 2022-09-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220903_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user',
            new_name='owner',
        ),
    ]
