# Generated by Django 4.1 on 2022-09-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_user_products_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='owner',
            new_name='user',
        ),
    ]
